### PR TITLE
Adding the requirements.txt file to nearup

### PR DESCRIPTION
**Pull request by chefsale**

### CODE REVIEW

**Review by frol — CHANGES_REQUESTED** [review]
I don't see a use of these packages, so I think we should not add it separately from the code uses them.

**Comment by chefsale** [comment]
The problem is we have to make people install the packages before because nearup pulls every commit and if the packages aren't installed all nearup nodes will break. That's one of the reasons why I was proposing publishing a pip package and then update only on new releases instead of the current code which updates on every commit in master. So, now we have to kindly ask all the validators to install all these packages upfront.

**Review by ailisp — CHANGES_REQUESTED** [review]
I agree with @frol requirements should be included as part of usage. Also, as discussed in chat, packages with c extensions (psutils) is troublesome to install with eggs. Do this package have c extensions? if not we can still packages them.

**Comment by ailisp** [comment]
I suggest we switch to pre-packaged nearup with bazel or app image right now, and change the `nearup` entry script, which instead of do a git pull self-update, doing a `download from s3/github release` self update. Need to be careful for this first transitional update. After that, new process will be: check github release -> self update by download new nearup release bundle -> run with new nearup and this doesn't break existing user experience. (self update will be a manually command `nearup update`, given self-update is downloading a binary which is not as fast as a git pull)

**Comment by chefsale** [comment]
Exactly that would be the best solution, will do that.

**Comment by frol** [comment]
> people install the packages before because nearup pulls every commit and if the packages aren't installed all nearup nodes will break.

Let's implement a boot script which does not require any external dependencies, and which role will always check the availability of the required packages (system and python ones) before running nearup main script. Note, to check if we have all the python dependencies, we just wrap the `main` function call with `try/except ImportError`. We may also install the dependencies there as well, using a dedicated virtualenv.

> I suggest we switch to pre-packaged nearup with bazel or app image right now

Will we package Python as well? C-extensions are Python-version sensitive, so we will need to have a separate package for each Python version then for each OS.

**Comment by ailisp** [comment]
> Will we package Python as well? C-extensions are Python-version sensitive, so we will need to have a separate package for each Python version then for each OS.

Yes with appimage: https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps. Not sure for bazel but probably also true.

**Comment by frol** [comment]
I find it ridiculous that nearup will be magnitude bigger than the neard itself :smile: 

BTW, we need to make sure that the watcher works fine inside such a packaged environment. Also, we may want to use an existing supervisor solution instead of our custom watcher.

**Comment by chefsale** [comment]
Hmm, not sure if which existing solution should we use if we plan to have online updates of nearup? I was talking to @mhalambek just to use systemd for running the nodes instead on linux, but if we want to have the updates we could pull the binary stop and start with systemd only instead of using the current implementation. As well we talked about totally removing the current spawning of docker images, as it should be most likely other way around: nearup should be dockerized, not the other way around.

**Comment by ailisp** [comment]
I don't suggest systemd as default, as it doesn't work on mac and harder for user to update. We can provide a command like `nearup install systemd` to generate systemd config file for user who want to run with systemd, but still they should use nearup to manage updates and configurations.

**Comment by chefsale** [comment]
We can run systemd for linux only.

**Comment by chefsale** [comment]
We would have to run on linux only :)

**Comment by ailisp** [comment]
> I find it ridiculous that nearup will be magnitude bigger than the neard itself 😄

Yeah this was the major reason we tried to use almost system builtin packages (python3 with only std lib, curl, git). But we'll benefit from this approach, say once we move to rust nearup, our bootstrapping script just download the rust binary to replace the python binary, user doesn't even know that.

> BTW, we need to make sure that the watcher works fine inside such a packaged environment. Also, we may want to use an existing supervisor solution instead of our custom watcher.

Current watch logic should be simple enough to replace with a bash script so it maybe not necessary, but we should test inside packaged env for sure

**Comment by ailisp** [comment]
FYI we have a script to create systemd for user: https://github.com/nearprotocol/nearcore/blob/master/scripts/create_service.py
But i don't suggest we use it as default way to run nearup, just optional way

**Pull request closed without merging**
