### PR TITLE
check is old watcher running via kill(2)

### PR DESCRIPTION
**Pull request by kucharskim**
Addresses near/nearup#170

Test plan:

```
$ nearup stop

$ cat /home/mikolaj/.nearup/watcher.pid
841382

$ ls -l /home/mikolaj/.nearup/watcher.pid
-rw-r--r-- 1 mikolaj 5018 6 Feb 23 10:41 /home/mikolaj/.nearup/watcher.pid

$ nearup run testnet
2021-02-23 11:02:25.826 INFO nearup - run: Home directory is /home/mikolaj/.near/testnet...
2021-02-23 11:02:25.826 WARNING watcher - check_watcher_file: Old Nearup watcher PID file /home/mikolaj/.nearup/watcher.pid found.
2021-02-23 11:02:25.826 INFO nodelib - setup_and_run: Using officially compiled binary
2021-02-23 11:02:28.037 INFO util - download_binaries: Downloading latest deployed version for testnet
2021-02-23 11:02:28.037 INFO util - download_binaries: Downloading neard to /home/mikolaj/.nearup/near/testnet/neard from nearcore/Linux/1.18.0/3b70067a4c16d100ea396a5b3144c00aa45a03fd/neard...
2021-02-23 11:02:32.177 INFO util - download_binaries: Downloaded neard to /home/mikolaj/.nearup/near/testnet/neard...
2021-02-23 11:02:32.177 INFO util - download_binaries: Making the neard executable...
2021-02-23 11:02:48.569 INFO nodelib - genesis_changed: The genesis version is up to date
2021-02-23 11:02:50.438 INFO nodelib - print_staking_key: Stake for user 'chorus-one.pool.f863973.m0' with 'ed25519:6LFwyEEsqhuDxorWfsKcPPs324zLWTaoqk4o6RDXN7Qc'
2021-02-23 11:02:50.463 INFO nodelib - run: Node is running...
2021-02-23 11:02:50.464 INFO nodelib - run: To check logs call: `nearup logs` or `nearup logs --follow`
2021-02-23 11:02:50.464 INFO nodelib - run: Watcher is enabled. Starting watcher...
2021-02-23 11:02:50.464 INFO watcher - run_watcher: Starting the nearup watcher...
2021-02-23 11:02:50.464 WARNING watcher - check_watcher_file: Old Nearup watcher PID file /home/mikolaj/.nearup/watcher.pid found.

$ cat /home/mikolaj/.nearup/watcher.pid
841824

$ ls -l /home/mikolaj/.nearup/watcher.pid
-rw-r--r-- 1 mikolaj 5018 6 Feb 23 11:02 /home/mikolaj/.nearup/watcher.pid
```

### CODE REVIEW

**Comment by kucharskim** [comment]
Not sure should that be addressed also in `is_neard_running()`

**Comment by kucharskim** [comment]
I guess if I ever face this problem in `is_neard_running()` I will create new pull request. I think what is here will do.

**Comment by joe-bowman** [comment]
fwiw, lgtm.

**Review by chefsale — APPROVED** [review]
LGTM. Thanks for adding this functionality.

**Pull request merged**
